### ISSUE TITLE
Is the service shutdown?

### ISSUE THREAD

**Issue by Drjacky** [sammdec/punkapi-site#11]
<img width="1024" alt="Screen Shot 2021-04-17 at 17 00 04" src="https://user-images.githubusercontent.com/2296754/115119050-5f73b600-9f9e-11eb-8fb7-67847b132a9e.png">

If yes, is it shut down forever or we could hope it gets back?

**Comment by dianacpg** [comment]
Had the same problem!

**Comment by cahe1540** [comment]
I keep getting 'Access-Control-Allow-Origin' error on my app. Welp, looks like it's time to scrap my project.

**Comment by Drjacky** [comment]
<img width="498" alt="Screen Shot 2021-04-18 at 17 11 55" src="https://user-images.githubusercontent.com/2296754/115152497-3a984500-a069-11eb-82f3-f1c153ef847f.png">

Fixed.

**Comment by dianacpg** [comment]
I still get the 402:PAYMENT_REQUIRED

**Comment by Drjacky** [comment]
@dianacpg On the both web and app sides, I'm getting the response!
<img width="667" alt="Screen Shot 2021-04-19 at 09 54 06" src="https://user-images.githubusercontent.com/2296754/115209108-30bc2380-a0f5-11eb-867a-49c280ede841.png">

But, I'm gonna reopen the issue so, the owner could reach out to you.

**Comment by dianacpg** [comment]
It's working now! Thank you! Can you close the issue please?

**Comment by cahe1540** [comment]
Yeah, my app works again.
