### ISSUE TITLE
IDs don't match the beer number in DIY DOG

### ISSUE THREAD

**Issue by tonyhewison** [sammdec/punkapi-site#6]
Hi, love the API. Good work.

It looks like the IDs do not match the beer #number as published in DIY DOG. For example #170 is Hop Fiction, but that has ID 212 in the API.

Cheers

**Comment by sammdec** [comment]
Apologies for the massive delay on this but yeah the id's do not match as they were generated just alphabetically. This was due to the fact that there were duplicated ID's in the printed version of DIY dog
